### ISSUE TITLE
A Codon cluster Parallelization to yet improve the speed of the mapping pipeline

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/gwas-data-services#7]
It was discovered that the mapping pipeline skips a number of Rsids.

This cluster mode parallelization will first be used to run the newly implemented fix for the bug that skips some rsId.

It will be further improved to run the mapping pipeline for the full database remap in September 2023

**Comment by ljwh2** [comment]
waiting for review from @sprintell

**Comment by ljwh2** [comment]
Reviewed, to be deployed
